php:
- '7.4'

notifications:
  email:
    recipients:
      - lukerodgers90+travis@gmail.com
    on_success: change
    on_failure: always

jobs:
  include:
    - stage: "Uptime monitoring"
      script:
        - echo 'date.timezone = "Europe/London"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
        - php --version
        - php pong.php
      if: type IN (cron)

