php:
- '7.4'

notifications:
  email:
    recipients:
      - lukerodgers90+travis@gmail.com
    on_success: change
    on_failure: always

jobs:
  include:
    - stage: "Uptime monitoring"
      script:
        - php pong.php
      if: type IN (cron)

